# This is a basic workflow to help you get started with Actions

name: Grading-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
       - main
  pull_request:
    branches: 
       - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration dose not affect the pag-build event above
      - createed

  # Allows you to run this workflow manually from the Actions tab
  check_run:
    types: [rerequested, requested_action]
  repository_dispatch:
    types: [opened, deleted]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./action-a
        with:
           MY_NAME: "Adam"

      - name: npm install and build webpack
        run: |
          npm install
          npm run build
